services:
  db:
    image: postgres:16-alpine
    container_name: taskbot-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskbot
    ports:
      - "5432:5432"
    volumes:
      - taskbot_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d taskbot" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  taskbot_pgdata:
