[project]
name = "taskbot"
version = "0.2.0"
requires-python = ">=3.11"
dependencies = [
  "aiogram>=3.8.0",
  "environs>=11.0",
  "psycopg[binary,pool]>=3.2",
  "apscheduler>=3.10.4",
  "python-dateutil>=2.9.0.post0",
  "pydantic>=2.8.2"
]

[tool.ruff]
line-length = 100
